use super::XMLBuilder;
use super::XmlEvent;

impl XMLBuilder {
    pub(crate) fn open_comments_extended(mut self) -> Self {
        self.writer
            .write(
                XmlEvent::start_element("w15:commentsEx")
                    .attr(
                        "xmlns:wpc",
                        "http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas",
                    )
                    .attr(
                        "xmlns:cx",
                        "http://schemas.microsoft.com/office/drawing/2014/chartex",
                    )
                    .attr(
                        "xmlns:cx1",
                        "http://schemas.microsoft.com/office/drawing/2015/9/8/chartex",
                    )
                    .attr(
                        "xmlns:cx2",
                        "http://schemas.microsoft.com/office/drawing/2015/10/21/chartex",
                    )
                    .attr(
                        "xmlns:cx3",
                        "http://schemas.microsoft.com/office/drawing/2016/5/9/chartex",
                    )
                    .attr(
                        "xmlns:cx4",
                        "http://schemas.microsoft.com/office/drawing/2016/5/10/chartex",
                    )
                    .attr(
                        "xmlns:cx5",
                        "http://schemas.microsoft.com/office/drawing/2016/5/11/chartex",
                    )
                    .attr(
                        "xmlns:cx6",
                        "http://schemas.microsoft.com/office/drawing/2016/5/12/chartex",
                    )
                    .attr(
                        "xmlns:cx7",
                        "http://schemas.microsoft.com/office/drawing/2016/5/13/chartex",
                    )
                    .attr(
                        "xmlns:cx8",
                        "http://schemas.microsoft.com/office/drawing/2016/5/14/chartex",
                    )
                    .attr(
                        "xmlns:mc",
                        "http://schemas.openxmlformats.org/markup-compatibility/2006",
                    )
                    .attr(
                        "xmlns:aink",
                        "http://schemas.microsoft.com/office/drawing/2016/ink",
                    )
                    .attr(
                        "xmlns:am3d",
                        "http://schemas.microsoft.com/office/dr